export const mockCourses = [
  {
    id: "1",
    title: "Matemática PAES — Álgebra y Funciones",
    subject: "Matemática",
    description: "Domina álgebra, funciones, ecuaciones y gráficos para la PAES. Ejercicios resueltos con el estilo del examen real.",
    level: "PAES",
    imageUrl: null,
    published: true,
    videos: [
      { id: "v1", title: "Introducción a funciones", duration: 1800, order: 1 },
      { id: "v2", title: "Funciones lineales y cuadráticas", duration: 2400, order: 2 },
      { id: "v3", title: "Ecuaciones e inecuaciones", duration: 2100, order: 3 },
      { id: "v4", title: "Ejercicios tipo PAES", duration: 3000, order: 4 },
    ],
  },
  {
    id: "2",
    title: "Matemática PAES — Geometría",
    subject: "Matemática",
    description: "Figuras planas, sólidos, trigonometría y geometría analítica con enfoque PAES.",
    level: "PAES",
    imageUrl: null,
    published: true,
    videos: [
      { id: "v5", title: "Triángulos y ángulos", duration: 1500, order: 1 },
      { id: "v6", title: "Círculos y áreas", duration: 1800, order: 2 },
      { id: "v7", title: "Trigonometría básica", duration: 2200, order: 3 },
    ],
  },
  {
    id: "3",
    title: "Lenguaje — Comprensión Lectora PAES",
    subject: "Lenguaje",
    description: "Estrategias para textos literarios y no literarios. Manejo del tiempo y técnicas para responder preguntas PAES.",
    level: "PAES",
    imageUrl: null,
    published: true,
    videos: [
      { id: "v8", title: "Tipos de texto y estructura", duration: 1600, order: 1 },
      { id: "v9", title: "Inferencias y vocabulario contextual", duration: 1900, order: 2 },
      { id: "v10", title: "Textos argumentativos", duration: 2000, order: 3 },
    ],
  },
  {
    id: "4",
    title: "Ciencias — Biología Celular",
    subject: "Ciencias",
    description: "Célula, metabolismo, reproducción y genética. Base para la PAES de Ciencias.",
    level: "PAES",
    imageUrl: null,
    published: true,
    videos: [
      { id: "v11", title: "Estructura celular", duration: 1700, order: 1 },
      { id: "v12", title: "Respiración y fotosíntesis", duration: 2100, order: 2 },
    ],
  },
  {
    id: "5",
    title: "Inglés — Grammar & Vocabulary B1",
    subject: "Inglés",
    description: "Gramática esencial, vocabulario y comprensión de textos en inglés para PAES y 4° Medio.",
    level: "4° Medio",
    imageUrl: null,
    published: true,
    videos: [
      { id: "v13", title: "Present & Past Tenses", duration: 1400, order: 1 },
      { id: "v14", title: "Reading Comprehension", duration: 1800, order: 2 },
      { id: "v15", title: "Vocabulary in context", duration: 1600, order: 3 },
    ],
  },
  {
    id: "6",
    title: "Matemática 3° Medio — Probabilidad y Estadística",
    subject: "Matemática",
    description: "Probabilidad, estadística descriptiva e inferencial para el currículum de 3° Medio.",
    level: "3° Medio",
    imageUrl: null,
    published: true,
    videos: [
      { id: "v16", title: "Probabilidad básica", duration: 1500, order: 1 },
      { id: "v17", title: "Distribuciones", duration: 2000, order: 2 },
    ],
  },
]

export const mockTeachers = [
  {
    id: "t1",
    subject: "Matemática",
    hourlyRate: 15000,
    bio: "Profesor de matemáticas con 8 años de experiencia. Especialista en PAES. +200 alumnos preparados.",
    verificationStatus: "VERIFIED",
    user: { name: "Carlos Muñoz", avatar: null },
  },
  {
    id: "t2",
    subject: "Lenguaje",
    hourlyRate: 12000,
    bio: "Licenciada en Letras, docente de Lenguaje para enseñanza media y preuniversitario.",
    verificationStatus: "VERIFIED",
    user: { name: "Ana Torres", avatar: null },
  },
  {
    id: "t3",
    subject: "Ciencias",
    hourlyRate: 14000,
    bio: "Biólogo y docente. Preparo estudiantes para PAES Ciencias con metodología práctica.",
    verificationStatus: "VERIFIED",
    user: { name: "Diego Herrera", avatar: null },
  },
  {
    id: "t4",
    subject: "Inglés",
    hourlyRate: 13000,
    bio: "Profesora bilingüe con certificación Cambridge. Clases dinámicas con enfoque comunicativo.",
    verificationStatus: "VERIFIED",
    user: { name: "Valentina Soto", avatar: null },
  },
]

export const mockClasses = [
  {
    id: "c1",
    subject: "Matemática",
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
    duration: 60,
    hourlyRate: 15000,
    status: "SCHEDULED",
    maxStudents: 1,
    dailyRoomUrl: null,
    teacher: mockTeachers[0],
    bookings: [],
  },
  {
    id: "c2",
    subject: "Matemática",
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 48),
    duration: 90,
    hourlyRate: 15000,
    status: "SCHEDULED",
    maxStudents: 3,
    dailyRoomUrl: null,
    teacher: mockTeachers[0],
    bookings: [{ id: "b1" }],
  },
  {
    id: "c3",
    subject: "Lenguaje",
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 36),
    duration: 60,
    hourlyRate: 12000,
    status: "SCHEDULED",
    maxStudents: 1,
    dailyRoomUrl: null,
    teacher: mockTeachers[1],
    bookings: [],
  },
  {
    id: "c4",
    subject: "Ciencias",
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 72),
    duration: 60,
    hourlyRate: 14000,
    status: "SCHEDULED",
    maxStudents: 2,
    dailyRoomUrl: null,
    teacher: mockTeachers[2],
    bookings: [],
  },
  {
    id: "c5",
    subject: "Inglés",
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 96),
    duration: 60,
    hourlyRate: 13000,
    status: "SCHEDULED",
    maxStudents: 5,
    dailyRoomUrl: null,
    teacher: mockTeachers[3],
    bookings: [{ id: "b2" }, { id: "b3" }],
  },
]

export const mockSession = {
  student: {
    user: { id: "u1", name: "Felipe Estudiante", email: "alumno@demo.cl", role: "STUDENT" as const },
  },
  teacher: {
    user: { id: "u2", name: "Carlos Muñoz", email: "profesor@demo.cl", role: "TEACHER" as const },
  },
}
